### ISSUE TITLE
타일 및 화물 시스템 (알파)

### ISSUE THREAD

**Issue by fkdl0048** [fkdl0048/merchants-journey#1]
# 타일 및 맵 개발

알파 테스트 기준으로 화물 및 타일 기반 시스템 작업

- [x] #2
- [x] #4
- [x] #8
- [x] #7
- [x] #24

**Comment by fkdl0048** [comment]
- 24-11-11 1차 기능 구현 완료
  - 11-12일 오후 9시 30분에 기획분과 회의 후 추가 기능, 제한 사항등 브리핑

**Comment by fkdl0048** [comment]
- 24-11-12 개발 브리핑
  - #2 
  - #4 
  - 개발 내용 컨펌받고 다음 개발 기능 추가 #7

**Comment by wuxia-king** [comment]
@fkdl0048 정안님 쿼터뷰 한번 확인해주세요.

**Comment by fkdl0048** [comment]
- 11.23 알파 종료
