### ISSUE TITLE
현재 아키텍처 설명 문서 작성

### ISSUE THREAD

**Issue by fkdl0048** [fkdl0048/merchants-journey#37]
# 신표국기 아키텍처*(게임 구조) 설명

현재 게임 구조 코어 시스템에 대한 이해를 위해 문서를 작성함

## 현재 게임 구조

크게 GameState와 InGameState로 구분됨 두 상태 모두 State패턴으로 구현되어 있으며, 데이터는 [Util](https://github.com/fkdl0048/merchants-journey/blob/main/Assets/2.%20Scripts/Utils/Enums.cs)에 정리되어 있음 *같이 사용해야 하는 Enum데이터는 여기에 작성 부탁*

GameState란 크게 게임을 관장하는 상태를 말함 Boot, Title, InGame, Credits 등 큰 단위를 다룸 따라서 씬으로 분리함 이에 따라 상태를 변경하는 매니저를 [GameManager](https://github.com/fkdl0048/merchants-journey/blob/main/Assets/2.%20Scripts/Core/Manager/GameManager.cs)가 관장함 최대한 GamaManager는 가벼워야 함 불변속성을 보장해야 하며, 가능하다면 분리할 것 -> 다른 매니저나 SO로 뺄 것

InGame은 GameState가 InGame일 때 관리하게 되는 상태를 말하며, 이 상태는 local(Ingame씬)에서 관리됨, 이는 [InGameSceneController](https://github.com/fkdl0048/merchants-journey/blob/main/Assets/2.%20Scripts/Controller/InGameSceneController.cs)로 관리함

현재 게임 구조의 위계는 Manager, Controller, System의 접미어를 순서로 가짐 즉, Manager가 붙은 클래스가 가장 높은 위치 (Global에 위치)하고 이는 Scripts/Core에 정리해둠, [Controller](https://github.com/fkdl0048/merchants-journey/tree/main/Assets/2.%20Scripts/Controller)는 씬 마다 각각 붙으며 Boot, MainMenu, InGame 각각 씬에 컴포넌트로 부착되어 있음

System은 Controller에서 각각 필요한, 모듈화된 State나 시스템에 DI(dependency injection)하기 위해 구분함

### InGameState

좀 더 활용적인 예시를 말한다면 InGameState와 System, Controller의 관계에 대해서 설명함

```cs
// 중략..
    public class InGameSceneController : MonoBehaviour
    {
        [Header("Scene References")]
        [SerializeField] private GameUI gameUI;
        [SerializeField] private UnitSystem unitSystem;
        [SerializeField] private StageSystem stageController;
        [SerializeField] private AudioClip gameBGM;
        
        private Dictionary<InGameState, IInGameState> states;
        private IInGameState currentState;

        private void Awake()
        {
            InitializeStates();
        }

        private void Start()
        {
            InitializeGame();
        }

        private void InitializeStates()
        {
            states = new Dictionary<InGameState, IInGameState>
            {
                {
                    InGameState.UnitPlacement,
                    new UnitPlacementState(this, gameUI, unitSystem, stageController)
                },
                {
                    InGameState.Wave,
                    new BattleState(this, gameUI, stageController)
                },
                {
                    InGameState.StageClear,
                    new StageClearState(this, gameUI)
                },
                {
                    InGameState.StageOver,
                    new StageOverState(this, gameUI)
                },
                // stage fail state 추가..예정
            };
        }

// 중략..
        public void ChangeInGameState(InGameState newState)
        {
            currentState?.Exit();
            
            currentState = states[newState];
            currentState.Enter();
            
            Debug.Log($"Game State Changed to: {newState}");
        }
    
        private void Update()
        {
            currentState?.Update();
        }

        private void OnDestroy()
        {
            if (this.gameObject.scene.isLoaded)
            {
                currentState?.Exit();
            }
        }
        
    }
}
```

IInGameState라는 인터페이스를 활용하여 현재 InGame상태를 관리함 이는 현재 기획이 불안정하고 각각 상태가 독립적으로 관리되어야 추가 및 수정이 용이하기에 해당 구조를 채택함

각각 상태에 대한 정의는 [InGame/State](https://github.com/fkdl0048/merchants-journey/tree/main/Assets/2.%20Scripts/InGame/State)폴더에 모아둠

각각의 상태는 Mono가 아닌 CS클래스이기에 유니티 GUI로 보이지 않음, 즉 인게임에 존재하는 데이터를 사용하기 위해선 인젝션 받아야 함 -> 이를 관장하는 것이 Controller임 위를 보면 알 수 있지만 Controller는 독립적으로 구성된 UnitSystem(유닛 관리 관련 System, StateSystem 스테이지 관리 시스템) 이를 직렬화를 통해 씬에서 직접 연결함 Controller가 System에 의존하게 됨 (System은 뒤에서 설명하지만 독립적으로 구성되어야 함)

```cs
{
    InGameState.UnitPlacement,
    new UnitPlacementState(this, gameUI, unitSystem, stageController)
}
```

*stageController -> stageSystem으로 수정해야 하겠네요 수정하겠읍니다..*

이렇게 InGame에서 State를 동적 생성하여 책임을 분리하며 독립적으로 동작하는 System을 받아와서 해당 상태에서 활용하여 게임이 동작함, 중요한 점은 State로 관리되기에 수정이나 제거가 용이하다는 점 즉, 이런 구조를 유지하기 위해선 위에서 말한 Controller, Manager, System의 관계를 이해해야 함

System의 경우 State에서 직접 Manager을 사용하여 데이터를 받아오는 경우를 최대한 줄이고, State나 Controller가 방대해지는 것을 막기 위함임

예를 들어 InGameController가 모든 행위 (유닛배치, 업그레이드, 웨이브 관리 등) 모든 행위를 담당한다면 코드는 커지고 엉키게 되며 객체지향이 깨짐 -> 각각 컴포넌트, cs에 맞는 역할만 수행할 수 있도록 분리하는것이 핵심임,

## 유의사항

1. Manager는 싱글톤이기 때문에, 비지니스 로직과 인게임 로직을 명확하게 분리해야 함 즉, 인게임 로직이 싱글톤에 결합되면 안됨
2. State가 커진다면 System으로 분리할 것 마찬가지로 System도 덩치가 커진다면 분리할 것
3. Controller는 각 시스템에 분배, DI 하는 역할이지 다른 역할을 수행하면 안됨
4. 대부분의 이벤트는 코드로 작성하고 State나 씬이 변경될 때 Free할 것

**Comment by PakaDopa** [comment]
문서 감사합니다. 
예전에 혼자 프로젝트 했었을 때 사용한 FSM 방식이랑 비슷해서 분석하는데 어렵지는 않았습니다.
대신, 제가 병합을 하는 과정에서 패턴 불변성을 저해할 만한 것들은 미리 노티를 드릴 테니 한 번씩 검토해 주시면 좋을 것 같아요~
@fkdl0048

**Comment by fkdl0048** [comment]
@PakaDopa PR로 올려주시면 코드리뷰할 때 같이 말씀드릴게여
