### ISSUE TITLE
업그레이드 시스템 (ProtoType)

### ISSUE THREAD

**Issue by fkdl0048** [fkdl0048/merchants-journey#39]
# 업그레이드 시스템 (ProtoType)

## 11-28 작업 예상하여 설계

> 업그레이드 시스템에 대한 설계를 미리 그려봄

- 먼저 업그레이드 항목을 기획자가 수정할 수 있도록 엑셀로 만들어야 함
  - 데이터는 유닛 종족값(enum)
  - 업그레이드 수치
  - 가격
- 이를 Json, CSV로 읽어와서 데이터를 UpgraderSystem에 넣어줌 -> 스스로 초기화 단계예서 ResourceManager로 불러와서 값 설정
- UpgraderSystem을 DI받는 UpgradeState를 만듬 -> 현재 위치는 Battle이후로 생각
- 시작 시, UpgraderSystem과 UnitSystem을 토대로 UI를 채움
- 이후 UI에 맞게 시스템 구현 -> 내부 Update는 동작할 내용이 별로 없음 UI에서만 처리할 듯?

## 12-20 마무리

- 로딩씬
- 타이틀
- 설정창
- 월드맵
- 의뢰서, 아이템
- 클리어 결과
- 업그레이드

*작업 내용이 너무 많아서 정리는 나중에..*

**Comment by wuxia-king** [comment]
업그레이드 시스템 및 획득 재화 시스템 드라이브에 업데이트 했습니다.
확인하고 피드백 남겨주세요.

https://docs.google.com/spreadsheets/d/1m7xzzzPBcymHzcHNO8wL7gSMZYqxV89wru6EdlzG0FE/edit?gid=0#gid=0

**Comment by fkdl0048** [comment]
@wuxia-king 문서 위치도 같이 댓글에 주실 수 있나요?

**Comment by fkdl0048** [comment]
@wuxia-king UI배치랑 디자인도 같이 넘겨주시면 시험기간전에 제작하겠읍니당

**Comment by wuxia-king** [comment]
업그레이드 시스템 UI 조금 수정해야 될 것 같습니다. 내일이면 완료될 것 같아서 완료되면 댓글 남기도록 하겠습니다.

**Comment by wuxia-king** [comment]
피그마 링크 :
https://www.figma.com/design/LXlg6IApx6S0qSX3LFfRpW/%EC%8B%A0%ED%91%9C%EA%B5%AD%EA%B8%B0-%EC%95%8C%ED%8C%8C-UI?node-id=0-1&node-type=canvas&t=j8VBF53fEBXkaU9J-0
흐름도 정리 : 
https://docs.google.com/presentation/d/1ft1hE2mgM23PQFmibwhjhP-p8o7altMAbkDLGxOd74E/edit#slide=id.g31a9d21b4d1_0_167

업그레이드 시스템 추가 했습니다. 확인 부탁드립니다.

**Comment by fkdl0048** [comment]
문서를 잘 써주셔서 이거 구현 가능한지 판단하고 논의하는걸 목요일에 같이 점검하면 될 것 같습니다. @wuxia-king

**Comment by wuxia-king** [comment]
넵 확인했습니다. 다행이네요ㅎㅎ.
도움이 되실만한 문서 한 가지 추가했습니다.

게임 전체 구성 및 메인 기능 항목 추가 : 
https://docs.google.com/presentation/d/1ft1hE2mgM23PQFmibwhjhP-p8o7altMAbkDLGxOd74E/edit#slide=id.g31ba6277b89_0_0

**Comment by wuxia-king** [comment]
[2024.12.20 베타 수정 사항]
1. 의뢰서 및 아이템/스킬 선택 단계에서 의뢰서 부분 제외한 배경 화면 검은색 불투명도 박스 추가 -> 배경 부분은 클릭 안되게끔(우성)
2. 설정 버튼 클릭 시 설정 부분의 투명도는 100% 로 수정, 의뢰서와 마찬가지로 설정 부분 제외한 배경 화면 검은색 불투명도 박스 추가
3. 업그레이드 시스템 UI 배치가 화면 해상도에 따라서 달라지는 부분 수정
