### ISSUE TITLE
EnemySpawner 동작 방식 수정

### ISSUE THREAD

**Issue by PakaDopa** [fkdl0048/merchants-journey#40]
# Enemy Spawner

기존 방식: 랜덤으로 n초가 지나면 spawn
변경 방식: 마차가 일정 위치를 지나면, 해당 구역에 spawn에서 (어떤 몬스터)를 (몇 마리) 스폰
[기획안 드라이브 링크](https://docs.google.com/presentation/d/1N3_iKvMLW-34zgO_pURDfIVZHSMyz8N0PATpueqPQQg/edit#slide=id.g31a0e6c0173_0_2)

---

# 개발 방식

InGame의 State가 Wave 일 때, Init을 하는 것이 좋다고 판단하였으나, 
적군이 생성되고 전투를 하는 것은 결국 Stage 내부의 작은 시스템이라 판단했습니다.
따라서, Stage 내부에서 적군을 생성하는 스포너 스크립트를 작성하는 것이 낫다고 생각했습니다.

## 트리거 존

마차가 "어떤 구역"을 지나는 것을 판별하기 위한 트리거 존이 필요하고, 해당 트리거 존은 "어떤 스포너"에 신호를 날릴 수 있어야 합니다. 최대한 기획자가 수정하기 쉽도록 만들 예정입니다.

## 스포너

어떤 "트리거"가 신호를 보내면 "어떤 몬스터'를 "몇 마리" 스폰 하는 로직이 필요합니다.

![image](https://github.com/user-attachments/assets/3814a97e-204f-43db-91f9-615dbe9286e5)

**Comment by PakaDopa** [comment]
# EnemySpawner - Trigger

![image](https://github.com/user-attachments/assets/c7361d34-049c-419e-8dd8-4cbbe097af21)

# EnemySpawnerBasedTirgger 

![image](https://github.com/user-attachments/assets/3e62574c-0173-436b-954a-b635c05a1434)

---

# 다양한 Spawner 개발 예상

아닐 수도 있지만 추가될 수 있으니까..

![image](https://github.com/user-attachments/assets/2edb228d-88e9-4484-b38b-8d7fdc4c8ee5)

를 상속한 BasedTrigger.cs입니다.

![image](https://github.com/user-attachments/assets/39eed92f-3ac8-497c-8488-2267938e1873)

**Comment by wuxia-king** [comment]
https://docs.google.com/presentation/d/1N3_iKvMLW-34zgO_pURDfIVZHSMyz8N0PATpueqPQQg/edit#slide=id.g31af6116444_0_0

1. 적 유닛 스폰 조건
2. 페이즈 구역 별 스폰되는 유닛 수
업데이트 했습니다. 확인 부탁드려요.

**Comment by PakaDopa** [comment]
@wuxia-king 

적 유닛 스폰 조건에 대해서 건의하고 싶은게 있는데, 배치 가능한 마차의 타일 크기가 trigger에 들어오는 조건 대신에
트리거의 크기 자체를 키우는 게 더 기획하기 쉬우실 것 같은데 어떻게 생각하십니까? (개발하기에도ㅎㅎ..)
마차에 달려있는 충돌감지박스에 트리거를 검사하는 박스가 닿으면 스폰되도록 만들어져 있습니다.

<img width="460" alt="image" src="https://github.com/user-attachments/assets/98a1ac41-883a-4c58-97f8-bbd226bb8bdb">

지금 구현된 것은 위 사진에서 빨간색 체크로 해놓은 직육면체에, 빨간색 사각형이 닿으면 적이 스폰되는 방식입니다.
감지 범위를 늘리고 싶으면 직육면체의 크기만 키우면 되는 일인데, 기획안대로 만들어야 할 큰 이유가 있을까요?
전략적인 이유가 있다면 들어보고 그대로 개발하고 싶습니다!

궁금한 것은 코멘트 달아주시고, 카톡으로 한번 알려주십시오!

**Comment by wuxia-king** [comment]
궁금한 점,
트리거의 크기 자체를 키운다는게 빨간색 체크된 직육면체의 크기를 조절한다는 뜻인가요?

전투가 끝나고 각 페이즈에 진입하는 동안 쉬는 시간이 짧게라도 생긴다면 우성님께서 말씀하신 방법으로 진행되도 상관 없습니다.
페이즈 간 시간 텀이 생길지에 대해서만 회의 때 얘기하면 될 것 같네요.

**Comment by PakaDopa** [comment]
일단 닫아놓겠습니다.
