### ISSUE TITLE
아군 프리팹이 생성되고 난 뒤, 그 자리를 유지하게끔 수정

### ISSUE THREAD

**Issue by PakaDopa** [fkdl0048/merchants-journey#42]
기존에는 마차 꼬랑지를 졸졸 따라다니는 방식에서 그 자리에 붙어있도록 수정했습니다.
아래는 구현된 gif인데, 수정해야 할 것이 있다면 코멘트 달아주십시오!

![GIF 2024-11-30 오후 3-35-09](https://github.com/user-attachments/assets/58b52f74-be4e-42a7-93ba-40be09040328)

전투 후, 잘 돌아옵니다.

**Comment by wuxia-king** [comment]
GIF 를 봤을때는 아주 좋습니다.
질문이 하나 있는데 전투 후에 잘 돌아온다는 것은 전투 조건도 모두 충족시키면서 잘 돌아온다는 뜻일까요?

**Comment by PakaDopa** [comment]
지금은 일단, 마차와 표차의 거리가 벌어지더라도 강제로 돌아오지는 않습니다. (개발할 예정)

적과의 조우 이후,
적은 아군에게
아군은 적에게 돌진을 하고 전투를 한 뒤, 전투가 끝나면 돌아오도록 만들어져 있습니다.

이제 추가적으로 전투 중에도, 만약 마차와 거리가 너무 멀어진다면 돌아오도록 수정할 예정입니다.

**Comment by PakaDopa** [comment]
완료
