### ISSUE TITLE
표사 유닛 묶어서 이동할 때 하나의 타일로 이동하도록 수정

### ISSUE THREAD

**Issue by PakaDopa** [fkdl0048/merchants-journey#43]
1. 하나의 타일에 3개의 유닛이 들어가도록 배치
2. 걔네를 선택하면 한 묶음으로 이동하도록 변경

**Comment by wuxia-king** [comment]
하나의 타일에 3개의 유닛이 들어가도록 수정 부탁드립니다.

**Comment by wuxia-king** [comment]
그리고 아군 실시간 조정에 있어서 시간이 느려지는 효과가 있어야 할 것 같습니다.
아군 군집 선택 -> 시간이 느려짐 -> 이동 희망하는 타일 클릭 -> 시간이 원래대로 돌아오며 아군 유닛 이동

래퍼런스 :
https://youtu.be/v-RCIXFW17s?t=2822

**Comment by PakaDopa** [comment]
잠시중단
